// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReceptekWebAPI.Data;

#nullable disable

namespace ReceptekWebAPI.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260130092421_Mentett")]
    partial class Mentett
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ReceptekWebAPI.Entities.Cimke", b =>
                {
                    b.Property<int>("CimkeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CimkeNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CimkeId");

                    b.ToTable("Cimkek");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.MentettRecept", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceptId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MentveEkkor")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReceptId1")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "ReceptId");

                    b.HasIndex("ReceptId");

                    b.HasIndex("ReceptId1");

                    b.ToTable("MentettReceptek");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.Recept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ElkeszitesiIdo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hozzavalok")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Leiras")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NehezsegiSzint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Receptek");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.ReceptCimke", b =>
                {
                    b.Property<Guid>("ReceptId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CimkeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReceptId", "CimkeId");

                    b.HasIndex("CimkeId");

                    b.ToTable("ReceptCimkek");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.MentettRecept", b =>
                {
                    b.HasOne("ReceptekWebAPI.Entities.Recept", "Recept")
                        .WithMany()
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReceptekWebAPI.Entities.Recept", null)
                        .WithMany("MentettByUsers")
                        .HasForeignKey("ReceptId1");

                    b.HasOne("ReceptekWebAPI.Entities.User", "User")
                        .WithMany("MentettReceptek")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recept");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.Recept", b =>
                {
                    b.HasOne("ReceptekWebAPI.Entities.User", "User")
                        .WithMany("Receptek")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.ReceptCimke", b =>
                {
                    b.HasOne("ReceptekWebAPI.Entities.Cimke", "Cimke")
                        .WithMany("ReceptCimkek")
                        .HasForeignKey("CimkeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReceptekWebAPI.Entities.Recept", "Recept")
                        .WithMany("ReceptCimkek")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cimke");

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.Cimke", b =>
                {
                    b.Navigation("ReceptCimkek");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.Recept", b =>
                {
                    b.Navigation("MentettByUsers");

                    b.Navigation("ReceptCimkek");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.User", b =>
                {
                    b.Navigation("MentettReceptek");

                    b.Navigation("Receptek");
                });
#pragma warning restore 612, 618
        }
    }
}
