// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReceptekWebAPI.Data;

#nullable disable

namespace ReceptekWebAPI.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260212080754_AddReceptKommentek")]
    partial class AddReceptKommentek
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ReceptekWebAPI.Entities.Cimke", b =>
                {
                    b.Property<int>("CimkeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CimkeNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CimkeId");

                    b.ToTable("Cimkek");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.Like", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceptId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LikeoltaEkkor")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "ReceptId");

                    b.HasIndex("ReceptId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.MentettRecept", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceptId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MentveEkkor")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "ReceptId");

                    b.HasIndex("ReceptId");

                    b.ToTable("MentettReceptek");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.Recept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ElkeszitesiIdo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FeltoltveEkkor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Hozzavalok")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KepFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("KepUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Leiras")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NehezsegiSzint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Receptek");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.ReceptCimke", b =>
                {
                    b.Property<Guid>("ReceptId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CimkeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReceptId", "CimkeId");

                    b.HasIndex("CimkeId");

                    b.ToTable("ReceptCimkek");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.ReceptKomment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IrtaEkkor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ReceptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Szoveg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceptId");

                    b.HasIndex("UserId");

                    b.ToTable("ReceptKommentek");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.Like", b =>
                {
                    b.HasOne("ReceptekWebAPI.Entities.Recept", "Recept")
                        .WithMany()
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReceptekWebAPI.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recept");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.MentettRecept", b =>
                {
                    b.HasOne("ReceptekWebAPI.Entities.Recept", "Recept")
                        .WithMany("MentettReceptek")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReceptekWebAPI.Entities.User", "User")
                        .WithMany("MentettReceptek")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recept");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.Recept", b =>
                {
                    b.HasOne("ReceptekWebAPI.Entities.User", "User")
                        .WithMany("Receptek")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.ReceptCimke", b =>
                {
                    b.HasOne("ReceptekWebAPI.Entities.Cimke", "Cimke")
                        .WithMany("ReceptCimkek")
                        .HasForeignKey("CimkeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReceptekWebAPI.Entities.Recept", "Recept")
                        .WithMany("ReceptCimkek")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cimke");

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.ReceptKomment", b =>
                {
                    b.HasOne("ReceptekWebAPI.Entities.Recept", "Recept")
                        .WithMany("Kommentek")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReceptekWebAPI.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recept");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.Cimke", b =>
                {
                    b.Navigation("ReceptCimkek");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.Recept", b =>
                {
                    b.Navigation("Kommentek");

                    b.Navigation("MentettReceptek");

                    b.Navigation("ReceptCimkek");
                });

            modelBuilder.Entity("ReceptekWebAPI.Entities.User", b =>
                {
                    b.Navigation("MentettReceptek");

                    b.Navigation("Receptek");
                });
#pragma warning restore 612, 618
        }
    }
}
